# Ref: https://taskfile.dev/reference/schema

version: '3'

vars:
  API_BASE_URI: "http://localhost:8080/v1/projects/feedface-cafe-beef-feed-facecafebeef"
  CURL_ARGS: "-v --fail-with-body"

tasks:
  run:
    set: ["e", "u", "x", "pipefail"]
    cmds:
      - go mod tidy
      - go generate ./...
      - go run -race cmd/main.go

  # La Vie En Rose mode
  test-happy-path:
    set: ["e", "u", "x", "pipefail"]
    cmds:
      - |

        # Test All GETs with pristine DB
        curl {{ .CURL_ARGS }} "{{ .API_BASE_URI }}/building_limits" | jq .
        curl {{ .CURL_ARGS }} "{{ .API_BASE_URI }}/split_building_limits" | jq .
        curl {{ .CURL_ARGS }} "{{ .API_BASE_URI }}/height_plateaus" | jq .

        # Create building limits
        curl {{ .CURL_ARGS }} -X PATCH --data @testdata/happypath/building_limits.geojson "{{ .API_BASE_URI }}/building_limits" | jq .

        # Create height plateaux
        curl {{ .CURL_ARGS }} -X PATCH --data @testdata/happypath/height_plateaux.geojson "{{ .API_BASE_URI }}/height_plateaus" | jq .

        # Fetch the limits
        curl {{ .CURL_ARGS }} "{{ .API_BASE_URI }}/split_building_limits" | jq .

  test-integration:
    set: ["e", "u", "x", "pipefail"]
    ignore_error: true # design rule violations suppose to be failing
    cmds:
      - task: test-integration-dre-building-limits-overlapped
      - task: test-integration-dre-building-limits-not-closed
      - task: test-integration-dre-building-limits-not-polygon
      - |

        # Malformed JSON
        curl -v --data '\{wat"data": \{\}\}' -X PATCH "{{ .API_BASE_URI }}/building_limits" | jq .
      - task: test-integration-dre-splits


  # Make sure we don't crash and burn due to something small and stupid
  # test-smoke:
  #   set: ["e", "u", "x"]

  # Test a few API calls with
  test-stress:
    set: ["e", "u", "x", "pipefail"]
    cmds:
      # PATCH
      - hyperfine "curl -v --data @testdata/happypath/building_limits.geojson -X PATCH '{{ .API_BASE_URI }}/building_limits' | jq ."

      # GET
      - hyperfine "curl -v '{{ .API_BASE_URI }}/building_limits' | jq ."


  test-integration-dre-building-limits-overlapped:
    set: ["e", "u", "x", "pipefail"]
    cmds:
      - |

        curl {{ .CURL_ARGS }} -X PATCH --data @testdata/dre/collection/err_overlapped.geojson "{{ .API_BASE_URI }}/building_limits" | jq .

  test-integration-dre-building-limits-not-closed:
    set: ["e", "u", "x", "pipefail"]
    cmds:
      - |

        curl {{ .CURL_ARGS }} -X PATCH --data @testdata/dre/collection/err_not_closed.geojson "{{ .API_BASE_URI }}/building_limits" | jq .

  test-integration-dre-building-limits-not-polygon:
    set: ["e", "u", "x", "pipefail"]
    cmds:
      - |

        curl {{ .CURL_ARGS }} -X PATCH --data @testdata/dre/collection/err_not_polygon.geojson "{{ .API_BASE_URI }}/building_limits" | jq .

  test-integration-dre-splits:
    set: ["e", "u", "x", "pipefail"]
    cmds:
      - |

        # Load building limits
        curl {{ .CURL_ARGS }} -X PATCH --data @testdata/dre/splits/err_not_polygon.geojson "{{ .API_BASE_URI }}/building_limits" | jq .

  # test-integration-dre-building-limits-self-intersection:
  #   set: ["e", "u", "x", "pipefail"]
  #   cmds:
  #     - |

  #       curl {{ .CURL_ARGS }} -X PATCH --data @testdata/dre/collection/err_self_intersection.geojson "{{ .API_BASE_URI }}/building_limits" | jq .
