// Code generated by "stringer -type=DesignRuleViolation -output=zz_generated_dre.stringer.go"; DO NOT EDIT.

package construction

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DesignRuleViolationOverlapped-0]
	_ = x[DesignRuleViolationNotClosed-1]
	_ = x[DesignRuleViolationNotPolygon-2]
	_ = x[DesignRuleViolationOutOfBound-3]
}

const _DesignRuleViolation_name = "DesignRuleViolationOverlappedDesignRuleViolationNotClosedDesignRuleViolationNotPolygonDesignRuleViolationOutOfBound"

var _DesignRuleViolation_index = [...]uint8{0, 29, 57, 86, 115}

func (i DesignRuleViolation) String() string {
	if i < 0 || i >= DesignRuleViolation(len(_DesignRuleViolation_index)-1) {
		return "DesignRuleViolation(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DesignRuleViolation_name[_DesignRuleViolation_index[i]:_DesignRuleViolation_index[i+1]]
}
